#!/bin/bash

#Custermize this for your application
APPLICATION_FILE_PATH=ArduBlockInstallBASH.sh

#Parameters
PRODUCT_HOME=/Library/__PRODUCT__/__VERSION__

echo "Post installation process started"

#Change permissions in home directory
echo "Change permissions in product home"
cd ${PRODUCT_HOME}
chmod -R 755 .
[ -d /usr/local/bin ] || mkdir /usr/local/bin

bash ${APPLICATION_FILE_PATH}

echo "Post installation process finished"
